config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  devise_for :users

  resources :phrases
  get 'phrase/random', to: 'phrases#random'
  get '*path', to: 'phrase#index' unless Rails.env.development?

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  belongs_to :user
  before_save :downcase_phrase

  def downcase_phrase
    first_word.downcase!
    second_word.downcase!
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :phrases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: :create

  def after_sign_in_path_for(resource)
    phrases_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController

  before_action :set_phrase, only: [:show, :edit, :update, :destroy]

  def index
    @phrases = Phrase.order(created_at: :desc)
  end

  def show
  end

  def new
    @phrase = Phrase.new
  end

  def create
    @phrase = Phrase.create(phrase_params)
    @phrase.user_id = current_user.id
    if @phrase.save
      redirect_to phrases_path, notice: "Saved"
    else
      render 'new', notice: "Something went wrong, we'll look into it"
    end
  end


  def edit
  end

  def update
    @phrase.update(phrase_params)
    redirect_to phrase_path(@phrase)
  end

  def destroy
    @phrase.destroy
    redirect_to phrases_path, notice: "Deleted"
  end

  def random
    # @phrase = Phrase.order('RANDOM()').first
    @phrase = Phrase.all.sample
  end

  private

  def phrase_params
    params.require(:phrase).permit(:first_word, :second_word, :color, :user_id)
  end

  def set_phrase
    @phrase = Phrase.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @phrases = Phrase.where("user_id = ?", @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>phrase palette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-background">
  <div class="grid-container">
    <div class="home-title-container text-center">
      <h1><%= link_to 'phrase palette', phrases_path, id: 'homeHeader' %></h1>
    </div>
  </div>
  <div class="fixed-bottom phrase-entry-box">
    <div class="col-sm-4">

    </div>
    <div class="col-sm-4">
      <!-- midde -->
    </div>
    <div class="col-sm-4 phrase-navigation">
      <span aria-label="new" data-microtip-position="top-left" role="tooltip">
        <%= link_to ('<i class="fa fa-plus"></i>').html_safe, new_phrase_path, class: "trim" %>
      </span>
      <span aria-label="random phrase" data-microtip-position="top-left" role="tooltip">
        <%= link_to ('<i class="fa fa-random"></i>').html_safe, phrase_random_path, class: "trim"  %>
      </span>
      <span aria-label="library" data-microtip-position="top-left" role="tooltip">
        <%= link_to ('<i class="fa fa-archive"></i>').html_safe, phrases_path, class: "trim" %>
      </span>
      <span aria-label="my palette" data-microtip-position="top-left" role="tooltip">
        <%= render 'users/user_icon' %>
      </span>
    </div>
  </div>
</div>

app/views/phrases/_form.erb
<div class="phrase-container" id="newPhraseBackground">
  <div class="fixed-bottom phrase-entry-box">
    <%= simple_form_for(@phrase) do |f| %>
    <div class="phrase-data-container trim">
      <div class="col-sm-4 col-md-4 hex-form">
        <div aria-label="select color (spacebar for random)" data-microtip-position="top-right" data-microtip-size="small" role="tooltip" id="colorMicrotipBox">
          <%= f.input :color, as: :minicolors, label:false, placeholder: "#", input_html: {data: {
            minicolors: { position: :top }}}, class: "phrase-form-field" %>
        </div>
      </div>
      <div class="col-sm-3 col-md-4 words-form">
        <%= f.text_field :first_word, value: Bazaar.super_adj.downcase, placeholder: ".....", class: "phrase-form-field" %>
        <%= f.text_field :second_word, value: Bazaar.super_item.downcase, placeholder: ".....", class: "phrase-form-field" %>
      </div>
      <div class="col-sm-4 col-md-4 new-phrase-buttons">
        <span id="copyHexTooltip" aria-label="copy hex" data-microtip-position="top-left" data-microtip-size="fit" role="tooltip">
          <i class="fa fa-clone" id="copyHex" onClick="copyHexToClipboard()"></i>
        </span>
        <%= button_tag type: 'submit', class: "trim", id: "formSubmit" do %>
        <span aria-label="save" data-microtip-position="top-left" data-microtip-size="fit" role="tooltip">
          <i class="fa fa-save" aria-hidden="true"></i>
        </span>
        <% end %>
        <span aria-label="clear phrase" data-microtip-position="top-left" data-microtip-size="fit" role="tooltip">
          <i class="fa fa-undo trim" id="clearPhrase" onClick="clearPhrase()"></i>
        </span>
        <span id="clearWords" aria-label="random phrase" data-microtip-position="top-left" data-microtip-size="fit" role="tooltip">
          <%= link_to ('<i class="fa fa-random"></i>').html_safe, phrase_random_path, class: "trim" %>
        </span>
        <span aria-label="library" data-microtip-position="top-left" data-microtip-size="fit" role="tooltip">
          <%= link_to ('<i class="fa fa-archive"></i>').html_safe, phrases_path, class: "trim" %>
        </span>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/phrases/_phrase.html.erb
<div class="phrase-container" style="background-color: <%= @phrase.color %>">
  <div class="col-sm-4 col-sm-offset-4">
     <h1 class="phrase-name trim"><%= @phrase.first_word %> <%= @phrase.second_word %></h1>
  </div>
  <div class="fixed-bottom phrase-entry-box">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
      <h2 id="phraseHex" class="trim"><%= @phrase.color %></h2>
    </div>
    <div class="col-sm-4 phrase-navigation">
      <span id="copyHexTooltip" aria-label="copy hex" data-microtip-position="top-left" data-microtip-size="fit" role="tooltip">
        <i class="fa fa-clone trim" id="copyHex" onClick="copyHexToClipboard()"></i>
      </span>
      <span aria-label="new" data-microtip-position="top-left" role="tooltip">
      <%= link_to ('<i class="fa fa-plus"></i>').html_safe, new_phrase_path, class: "trim" %>
      </span>
      <% if current_user && current_user.id == @phrase.user_id %>
        <span aria-label="delete" data-microtip-position="top-left" role="tooltip">
          <%= link_to ('<i class="fa fa-trash"></i>').html_safe, phrase_path, method: :delete, data: { confirm: "Are you sure?" }, class: "trim" %>
        </span>
      <% end %>
      <span aria-label="random phrase" data-microtip-position="top-left" role="tooltip" id="tooltip">
        <%= link_to ('<i class="fa fa-random"></i>').html_safe, phrase_random_path, class: "trim"  %>
      </span>
      <span aria-label="library" data-microtip-position="top-left" role="tooltip">
        <%= link_to ('<i class="fa fa-archive"></i>').html_safe, phrases_path, class: "trim" %>
      </span>
    </div>
  </div>
</div>

app/views/phrases/edit.html.erb
<%= render 'form' %>

app/views/phrases/index.html.erb
<div class="container">
  <%= render 'shared/navbar' %>
  <div class="cards-container">
    <div class="row" id="cardRow">
        <% @phrases.each do |phrase| %>
            <div class="col-md-3 col-sm-6 col-xs-12" style="padding: 0px">
              <div class="card" style="background: <%= phrase.color %>">
                 <%= link_to phrase_path(phrase) do %>
                  <div class="card-body">
                  </div>
                  <div class="card-footer">
                    <div class="card-phrase" id="cardPhraseLink">
                      <%= phrase.first_word %> <%= phrase.second_word %>
                    </div>
                  <% end %>
                  <div class="card-hex">
                    <%= phrase.color %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
</div>

app/views/phrases/new.html.erb
<%= render 'form' %>

app/views/phrases/random.html.erb
<%= render 'phrase' %>

app/views/phrases/show.html.erb
<%= render 'phrase' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_nav_buttons.html.erb
<span aria-label="new" data-microtip-position="bottom-left" role="tooltip">
  <%= link_to ('<i class="fa fa-plus trim"></i>').html_safe, new_phrase_path %>
</span>
<span aria-label="random phrase" data-microtip-position="bottom-left" role="tooltip">
  <%= link_to ('<i class="fa fa-random trim"></i>').html_safe, phrase_random_path %>
</span>
<span aria-label="my palette" data-microtip-position="bottom-left" role="tooltip">
  <%= render 'users/user_icon' %>
</span>
<% if user_signed_in? %>
  <span aria-label="log out" data-microtip-position="bottom-left" role="tooltip">
    <%= link_to('<i class="fa fa-sign-out trim"></i>'.html_safe, destroy_user_session_path, method: :delete) %>
  </span>
<% end %>
<span aria-label="library" data-microtip-position="bottom-left" role="tooltip">
  <%= link_to ('<i class="fa fa-archive trim"></i>').html_safe, phrases_path, class: "trim" %>
</span>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-title">
    <h3 style="margin: 0px">
      <%= link_to 'phrase palette', root_path, id: "navTitleLink" %>
      <span class="index-name">
        <% if current_page?("/phrases") %>
          library
        <% end %>
      </span>
    </h3>
  </div>
  <div class="nav-buttons">
    <%= render 'shared/nav_buttons' %>
  </div>
</nav>

app/views/users/_user_icon.html.erb
<% if user_signed_in? %>
    <%= link_to ('<i class="fa fa-user trim"></i>').html_safe, user_path(current_user) %>
  <% else %>
      <%= link_to('<i class="fa fa-user trim"></i>'.html_safe, new_user_session_path)  %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <nav>
    <div class="nav-title">
      <h3 style="margin: 0px">
        <%= link_to 'phrase palette', root_path, id: "navTitleLink" %>
        <span class="index-name">my palette</span>
      </h3>
    </div>
    <div class="nav-buttons">
      <%= render 'shared/nav_buttons' %>
    </div>
  </nav>
    <div class="cards-container">
      <div class="row" id="cardRow">
          <% @phrases.each do |phrase| %>
              <div class="col-md-3 col-sm-6 col-xs-12" style="padding: 0px">
                <div class="card" style="background: <%= phrase.color %>">
                   <%= link_to phrase_path(phrase) do %>
                    <div class="card-body">
                    </div>
                    <div class="card-footer">
                      <div class="card-phrase" id="cardPhraseLink">
                        <%= phrase.first_word %> <%= phrase.second_word %>
                      </div>
                    <% end %>
                    <div class="card-hex">
                      <%= phrase.color %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
        </div>
      </div>
  </div>
</div>